apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: juno-platform
  namespace: argocd
spec:
  description: juno-platform project
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
      name: in-cluster
    - name: juno-lab-aks
      server: https://juno-lab-c6uths9x.hcp.norwayeast.azmk8s.io
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
