apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: juno-platform
  namespace: argocd
spec:
  description: juno-platform project
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceNamespaces:
    - "*"
