apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator-juno-lab
  namespace: juno-apps
spec:
  project: juno-platform
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.8.5
    helm:
      releaseName: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
